### ISSUE TITLE
syntax 

### ISSUE THREAD

**Issue by louieblu** [vincuska/vSpoofer#1]
line 97
    command = f"{volumeid_path} -nobanner {os.getenv("SystemDrive")} {new_serial_number}"
                                                      ^^^^^^^^^^^
SyntaxError: f-string: unmatched '('

nice little project gonna try make a nice gui 
discord louieblu99

**Comment by vincuska** [comment]
for some reason it works fine for me
i've sent you a friend request on discord

"gecis"
